-- Create the user_favorites table
CREATE TABLE public.user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    paper_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT user_favorites_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES public.papers(id) ON DELETE CASCADE,
    CONSTRAINT user_favorites_user_id_paper_id_key UNIQUE (user_id, paper_id)
);

-- Enable Row Level Security
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;

-- Create policies for user_favorites
CREATE POLICY "Allow users to view their own favorites"
ON public.user_favorites
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own favorites"
ON public.user_favorites
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own favorites"
ON public.user_favorites
FOR DELETE
USING (auth.uid() = user_id);

-- Add comments to the table and columns
COMMENT ON TABLE public.user_favorites IS 'Stores the favorite papers for each user.';
COMMENT ON COLUMN public.user_favorites.user_id IS 'The ID of the user who favorited the paper.';
COMMENT ON COLUMN public.user_favorites.paper_id IS 'The ID of the favorited paper.';